### PR TITLE
Fix unit conversion

### PR DESCRIPTION
**Pull request by nocollier**
Unit conversion in ILAMB is bugged due to the unexpected behavior of `is_convertible()`. For example: 

```
In [1]: from cf_units import Unit                                                                                                                                            
In [2]: u = Unit('g')                                                                                                                                                        
In [3]: u.is_convertible("1/g") 
Out[3]: True
```
This produces unexpected results in very few cases in ILAMB runs and, as far as I know, is only an issue with the magnitude of period means that we report. This patch switches the logic when checking if we need to multiply or divide by density/molar mass to be definitive and fixes the error which initially brought this to my attention. Thanks Daniel Kennedy.

### CODE REVIEW

**Comment by minxu74** [comment]
@nocollier did it affect all metrics? or just some of them?

**Comment by nocollier** [comment]
I didn't know about the problem because nothing in our standard ILAMB runs hits it. It came out in the CLM Sparse runs,  which are running from the raw h0 output. So the ET was converted from a linear rate 'mm/s' to a mass flux rate 'g / m2 / s' (because that matches the observations) and then back to 'mm d-1' for rendering in the table. I am not totally clear why this setup revealed the error that our other runs do not, but ET typically is provided in units of 'mass / area / time'.  

This should only affect period mean values which were scaled by density or molar mass. Please let me know if you observe odd behavior/changes. I will be checking scores of our CMIP5v6 run pre and post change, but as scores are unitless and based on an error which is invariant with respect to units, I do not expect changes.

**Comment by minxu74** [comment]
@nocollier Thanks a lot for clarification. Yes. It is a general practice in our community to use the "mm/s" instead of "kg/m2/s" for ET, PR and other water related fluxes by assuming the water density is 1000kg/m3. But the CF-units seems not to accept the conversion between "mm/s" and "kg/m2/s" because it does not think they are convertible. I do not know how this kind of conversions are handled in ILAMB?

**Comment by nocollier** [comment]
Yes, these kinds of conversions require the assumption of substance (mass
density = 998 kg m-3). Inside ILAMB I am checking if the original unit
divided by the target unit is off by a factor of the density:

if ((src_unit/tar_unit)/mass_density).is_dimensionless():

If so, then I scale the data by the density and change the original unit.
See here for the relevant code:

https://github.com/rubisco-sfa/ILAMB/blob/master/src/ILAMB/Variable.py#L859

It also handles molar mass as long as the substance is carbon. Not perfect,
but does the job for everything we have done until now.

**Pull request merged**
