### PR TITLE
FIX: Sneaky bugs reported by Patrick McGuire

### PR DESCRIPTION
**Pull request by nocollier**

### CODE REVIEW

**Comment by mcguirepatr** [comment]
Hi Nathan:
Thanks for trying to fix this.
It modifies the behavior, but not exactly how I expected.
The overall scores for the relationships are now missing for all the models, whereas I would only expect them to be missing for the relationships for the models that have missing data.
See this link:
https://gws-access.jasmin.ac.uk/public/ncas_climate/pmcguire/ILAMB_output/GCP_290824a/
Or this screenshot:
Screenshot 2024-08-29 at 14 07 27

I didn't rerun the whole ILAMB, I just reran ILAMB with these two lines in the Confrontation changed and I added a new model (SDGVMv9_24) prior to the rerun.
Can you take a 2nd look at it?
Thanks
Patrick McGuire

**Comment by nocollier** [comment]
Hey Patrick,

Thanks for the report. I need to try to create a small example where I can
reproduce the behavior. I have to finish a few reviews but will get bcak on
this as soon as I can.

Nate

**Comment by minxu74** [comment]
@nocollier I tried to look into the problem by open the UD (https://gws-access.jasmin.ac.uk/public/ncas_climate/pmcguire/ILAMB_output/GCP_290824a/dashboard.html). I found the results from UD and index.html were different, but they are supposed to be identical. The reason is that the content of scalars.json are different to scalar_database.json used by UD. The same problem also reported by #100 .

**Comment by nocollier** [comment]
This is a problem of me having bolted on things to ILAMB. Thanks Min, this gives me a place to start looking. I think the issue is that there are multiple places where we merge results. There is the OverallScore function of Confrontations, but then I also (later) wrote a harvest of all scalars and compute aggregations using pandas. I will track them all down and let's see if we can unify them so it is a single way.

**Comment by minxu74** [comment]
@nocollier Thanks a lot. I found the code and could fix the inconsistent problem if you are not available. But we need to discuss a way to compute composite scores and write the two json files consistently. We also could let index.html read the CMEC json file directly as the CMEC json file includes all the results and meta information.

**Comment by nocollier** [comment]
I believe the issue is that we need aggregation in 2 places:

1. Before generating the Dataset html pages. The score data is written into the html directly and so we need it at this level.
2. When leaving an artifact for use in the top level page.

I finished my reviews, will look at this today/tomorrow.

**Comment by mcguirepatr** [comment]
I ran out of space on my web server, so I am currently moving my ILAMB pages to another web server. (Just in case you're looking for any of them.)

**Comment by mcguirepatr** [comment]
Here are recent ILAMB links at my **new** web server:
https://gws-access.jasmin.ac.uk/public/landsurf_rdg/pmcguire/ILAMB_output/GCP_290824a/index.html
https://gws-access.jasmin.ac.uk/public/landsurf_rdg/pmcguire/ILAMB_output/GCP_290824a/dashboard.html

**Pull request merged**
