### PR TITLE
Add cmec-driver interface

### PR DESCRIPTION
**Pull request by acordonez**
### Summary
Add JSON and driver scripts for 7 ILAMB configurations to be run with [cmec-driver](https://github.com/cmecmetrics/cmec-driver). These configurations use the same parameters found under https://github.com/rubisco-sfa/ILAMB/tree/master/src/ILAMB/data. Additionally, there is a "custom" configuration that can run user-selected sections of the CMIP configuration.

### Data
All of the configurations rely on standard observational data that can be obtained with ilamb-fetch (or downloaded as part of the ILAMB tutorial in the case of the Sample configuration).

### Configuration list
CMIP
Custom
Diurnal
Forcings
ILAMB
IOMB
Sample

### How to run
Users should clone the cmec-driver and ILAMB directories.
Enter the cmec-driver clone directory. 
First, register ILAMB with cmec-driver, running:
`python cmec-driver.py register <path to ILAMB clone>`

cmec-driver takes an (optional) observations folder, a model folder, and an output folder name as inputs. Use the "DATA" directory housing the downloaded observations as the observations input. The model folder can be set up similarly to the "model_root" folder in the traditional ILAMB usage. The output folder will be created if it does not exist.

An example command:
python cmec-driver.py run -obs DATA/ model/ output/ ILAMB/Sample

In this example, all of the results will be located under output/ILAMB/Sample

### Custom configuration
A custom configuration is provided to let users run subsets of the CMIP configuration. After registering the ILAMB module, users may edit the cmec-driver configuration file config/cmec.json to specify which confrontations to run. Provide the names of the H1 or H2 level categories to run as a list under "ILAMB/Custom": "confrontations".
For example:
    "ILAMB/Custom": {
        "confrontations": [
            "Surface Upward SW Radiation",
            "Albedo"
        ]
    },
will run the Surface Upward SW Radiation and Albedo sections of [CMIP.cfg](https://github.com/rubisco-sfa/ILAMB/blob/master/src/ILAMB/data/cmip.cfg). 

### cfg_to_json.py
This script converts an ILAMB .cfg file into JSON format and places the results into an existing json under the "default_paramters" key. This is to help developers with creating and maintaining the cmec interface JSON files in ILAMB/cmec-driver.

### CODE REVIEW

**Comment by acordonez** [comment]
@nocollier @minxu74 Here are my proposed changes to set up an interface to run the ILAMB metrics through cmec-driver. I'm hoping to make this as useful and unobtrusive as possible and would welcome your feedback.

**Comment by nocollier** [comment]
This looks fine to me, unobtrusive and neatly presented. Shall I merge?

**Comment by minxu74** [comment]
The PR looks good to me. The only problem to me is how we document these new features.  The PR itself is archived in the repository, but users may not look at the closed PR for details. @acordonez @nocollier

**Comment by acordonez** [comment]
@nocollier @minxu74 I like the idea of a cmec-driver "badge" or something similar. Instructions for running cmec-driver are available in the cmec-driver repo. I could add a README that points users to that documentation.

**Comment by acordonez** [comment]
@nocollier This is ready to merge now (forgot to add the IOMB data in iomb.json earlier). Did not add a README but I can still do that if you're interested.

**Comment by nocollier** [comment]
Let's merge as is for now, I am not too concerned about someone wandering into the repository and wondering what that CMEC thing is. I do think that the idea of a badge is worth thinking about. Turns out they are not hard to make:

https://img.shields.io/badge/CMEC-ready-brightgreen
badge

**Comment by acordonez** [comment]
> Let's merge as is for now, I am not too concerned about someone wandering into the repository and wondering what that CMEC thing is. I do think that the idea of a badge is worth thinking about. Turns out they are not hard to make:
> 
> https://img.shields.io/badge/CMEC-ready-brightgreen
> badge

@nocollier The badge looks great! Thanks for the suggestion, and feel free to use it.

**Pull request merged**
