### PR TITLE
Updates for CLM-specific issues

### PR DESCRIPTION
**Pull request by olyson**
I'm proposing a few changes here for CLM-specific issues.  At NCAR, we've been running off a "LMWG" branch but would now like to bring these changes to master in preparation for incorporating ILAMB into our new unified postprocessing and diagnostic package (CUPID: https://github.com/NCAR/CUPiD).
The changes proposed here are:

1. Make the scripts in /bin executable for user.  Right now they come as not executable when cloning the ILAMB repository.  So we have to do a chmod on these scripts when updating ILAMB.
2. Add CLM-specific variables to the permafrost confrontation
3. Add CLM-specific variables to the soil carbon confrontation
4. Add CLM-specific BGC and SP configuration files.  We would maintain these ourselves as ILAMB and its observational datasets change or are updated and then issue pull requests for these two files.

I've tested these successfully on our machine casper, but not on other machines.
Happy to entertain other methods of supporting these changes.

### CODE REVIEW

**Comment by nocollier** [comment]
Keith! Thanks for this, I believe the tests are failing because numpy released v2.0.0 and there are some backwards compatibility issues with other things in ILAMB. I will work on resolving this today.

**Comment by nocollier** [comment]
@olyson Can you rebase your branch again with master and push? I added some benign commits to master that will limit the version of numpy and that should fix the test errors.

**Comment by olyson** [comment]
Thanks Nate.  I ran "git rebase master PR1", but it says "Current branch PR1 is up to date." and I don't see the changes you made today in my branch.  I'll consult with the SEs here.

**Comment by nocollier** [comment]
I haven't done this too much, but if you go to your fork on github, I think you should be able to update it. It will say you are something like 5 commits behind and it can be merged/rebased automatically. Once you have updated your fork, you can run the commands  and I think they should work. The issue is that when you update your master you are only getting updates from your fork and not mine too.

**Comment by olyson** [comment]
Got it thanks.  I believe I am updated to latest master now.

**Comment by nocollier** [comment]
I am working on a few things with ILAMB right now, but in the coming week I will release 2.7.1 so you can tag it in your system.

**Comment by olyson** [comment]
Thanks!

**Pull request merged**
